-- Veículos cadastrados (vindos da aba VEÍCULOS). ativo = STATUS marcado na planilha.
insert into public.veiculos (placa, transportadora, tipo, motorista, entregador, ativo, obs) values
('TSF1G48', 'AMORIM', 'VAN', 'ARLISON', '', true, ''),
('PHY1I84', 'BZ TRANSP', '3/4', '', '', false, ''),
('PHG9176', 'CMG', 'TRUCK', '', '', false, ''),
('QZP1D54', 'CMG', 'TRUCK', '', '', false, ''),
('JWW5222', 'CMG', '3/4', 'JEFFERSON', '', true, ''),
('TAB5E78', 'CMG', 'TRUCK', '', '', false, ''),
('QZC4H93', 'CMG', 'HR', '', '', false, ''),
('NPB1J08', 'CMG', '3/4', '', '', true, ''),
('ENE9G76', 'HOK', 'TRUCK', '', '', false, ''),
('PHW6408', 'HOK', 'FIORINO', '', '', false, ''),
('PHY7A24', 'HOK', '3/4', '', '', true, ''),
('PHY7A04', 'HOK', '3/4', '', '', true, ''),
('QJS6F09', 'HOK', '3/4', '', '', true, ''),
('QIE8I24', 'HOK', '3/4', '', '', true, ''),
('PHY6J94', 'HOK', '3/4', '', '', true, ''),
('PHY6J84', 'HOK', '3/4', '', '', true, ''),
('PHY7A34', 'HOK', '3/4', '', '', true, ''),
('QZG0I99', 'HOK', 'FIORINO', '', '', true, ''),
('NPB7J34', 'HOK', '3/4', '', '', false, ''),
('TPP4D15', 'HOK', '3/4', '', '', true, ''),
('PHY7A44', 'HOK', '3/4', '', '', false, ''),
('PHY7A14', 'HOK', '3/4', '', '', true, ''),
('GHO6C81', 'HOK', '3/4', '', '', true, ''),
('BTZ4I89', 'HOK', 'TOCO', '', '', true, ''),
('GJK9B13', 'HOK', 'TOCO', '', '', true, ''),
('TSI6H75', 'JB TRANSP', 'HR', 'JOSÉ', '', true, ''),
('TSI6H95', 'JB TRANSP', 'HR', 'JARDEU', '', true, ''),
('NPB8611', 'MAMBA', 'TRUCK', '', '', false, ''),
('NOS6525', 'MAMBA', 'TRUCK', '', '', false, ''),
('JXV1957', 'MAMBA', '3/4', '', '', false, ''),
('PHD8475', 'MAMBA', '3/4', '', '', false, ''),
('PHD8465', 'MAMBA', '3/4', '', '', false, ''),
('PHV5649', 'MAMBA', 'TOCO', '', '', false, ''),
('NOJ4984', 'MAMBA', '3/4', '', '', false, ''),
('QZR6G12', 'MAMBA', 'TOCO', '', '', false, ''),
('PHZ4D84', 'MAMBA', '3/4', '', '', false, ''),
('JXS0I88', 'MAMBA', 'TRUCK', '', '', false, ''),
('NOY8499', 'MAMBA', '3/4', '', '', true, ''),
('NOS4583', 'MAMBA', '3/4', '', '', false, ''),
('QZK3I46', 'MAMBA', '3/4', '', '', false, ''),
('QZJ5A83', 'MAMBA', 'TOCO', '', '', false, ''),
('OAC6945', 'MAMBA', 'TOCO', '', '', false, ''),
('NOK2806', 'MAMBA', '3/4', '', '', true, ''),
('QZV6I05', 'MAMBA', '3/4', '', '', false, ''),
('QZV6H85', 'MAMBA', '3/4', '', '', false, ''),
('JXW8974', 'RALPH', '3/4', '', '', true, ''),
('NOW4523', 'RALPH', 'TOCO', '', '', false, ''),
('JXR2886', 'RALPH', '3/4', '', '', true, ''),
('JWV5646', 'SANTIAGO', '3/4', '', '', false, ''),
('BBT2D57', 'SEM NOME', 'CARRETA', '', '', false, ''),
('NPA6J18', 'SERVICE', '3/4', '', '', true, ''),
('JXV8074', 'TERCEIRO', '3/4', '', '', false, ''),
('PHX7A16', 'TERCEIRO', 'CAVALO', '', '', false, ''),
('UTP3H77', 'TERCEIRO', 'HR', '', '', true, '')
on conflict (placa) do nothing;
